pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // Update: BlurView (realne rozmycie tla pod paskiem statusu/nawigacji,
        // patrz app/build.gradle i EdgeToEdge.kt) jest publikowany przez Jitpack.
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = 'FA_ksiegowy'
include ':app'
